# .github/workflows/deploy.yml
name: Deploy to VPS



on:
  workflow_dispatch:
  push:
    branches: [master]   # runs only when you push/merge to master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Deploy via SSH git pull
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}



          script: |
            cd /var/www/estatein/wp-content/themes/estatein
            git pull origin main
